/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/building/model.glb 
Author: megatoastblaster (https://sketchfab.com/megatoastblaster)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/new-york-apartment-1535d54720774326a477f4933834e3d8
Title: New York Apartment
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Building(props) {
  const { nodes, materials } = useGLTF('/models/building/model.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.009, 0, 0]} rotation={[-Math.PI / 2, 0, 0.005]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, 0, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes['Door1_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} />
            <mesh geometry={nodes['Door1Knob_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[0.37, 0.14, 0.95]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
          </group>
          <group position={[-200, 1100, -70]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes['RoofAccess_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} />
            <mesh geometry={nodes['RoofHandle_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-0.35, 0, 0.8]} />
          </group>
          <group position={[170, 1100, 170]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes['AntennaeBase_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} />
            <mesh geometry={nodes['Antennae_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[0, 0, 0.9]} rotation={[0.65, -0.477, 2.599]} />
          </group>
          <group position={[275, 0, -150]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
            <mesh geometry={nodes['Door2_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} />
            <mesh geometry={nodes['Door2Handle_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-0.35, -0.1, 0.8]} />
          </group>
          <mesh geometry={nodes['Roof001_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[0, 1030, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['CornerStonesTop_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 310, -300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['PavementStones001_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-400, -10, 500]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['PavementEdge002_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-400, -10, 565]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Road002_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[0, -10, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['ShopFront012_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[0, 250, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['ShopFront017_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[0, 510, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['ShopFront098_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-200, 250, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['ShopFront100_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-200, 510, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['ShopFront101_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-200, 770, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['ShopFront102_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[200, 0, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['ShopFront104_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-200, 0, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['ShopFront105_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 0, 200]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['ShopFront106_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 0, 0]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['ShopFront107_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 0, -200]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['ShopFront108_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[200, 0, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['ShopFront109_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[0, 0, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['ShopFront110_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-200, 0, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['ShopFront111_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 0, -200]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['ShopFront112_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 0, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['ShopFront113_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 0, 200]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['ShopFront118_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[0, 770, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['ShopFront123_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-170, 0, 305]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['ShopFront128_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[200, 250, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['ShopFront129_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[200, 510, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['ShopFront130_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[200, 770, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['ShopFront134_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[0, 250, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['ShopFront135_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[0, 510, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['ShopFront136_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[0, 770, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['ShopFront144_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 510, 0]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['ShopFront145_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 770, 0]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['ShopFront147_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 510, 200]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['ShopFront152_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 250, 0]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['ShopFront155_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 250, 200]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['ShopFront157_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 770, 200]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['ShopFront163_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 770, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['ShopFront164_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 250, -200]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['ShopFront170_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 250, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['ShopFront171_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 510, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['ShopFront174_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 510, -200]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['ShopFront175_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 770, -200]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['ShopFront179_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[305, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['CornerStonesBot_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 30, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['GroundCeiling_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[0, 200, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Floor1Ceiling_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[0, 490, 290]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Floor2Ceiling_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[0, 750, 290]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Escape2_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 560, -100]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Escape3_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 820, -100]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['EscapeStair2_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[381, 570, -143]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['EscapeStair1_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[381, 310, -143]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['EscapeLadder_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[425, 305, 5]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Escape1_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 300, -100]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['WaterTower_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[140, 1180, -100]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Drain_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[310, 0, 260]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['FireHydrant_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 0, 500]} rotation={[-Math.PI / 2, 0, 0]} scale={86.171} />
          <mesh geometry={nodes['ManHole001_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[0, 0, 500]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['PavementEdge003_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[200, -10, 565]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Road003_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[200, -10, 598]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Trash_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[200, 0, 500]} rotation={[-Math.PI / 2, 0, 0]} scale={71.618} />
          <mesh geometry={nodes['TrafficLight_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-420, 0, 500]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['TrashBag003_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[151.685, -6.371, 531.843]} rotation={[-Math.PI / 2, 0, 0]} scale={23.11} />
          <mesh geometry={nodes['TrashBag004_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[329.945, -4.915, -15.67]} rotation={[-Math.PI / 2, 0, -1.598]} scale={27.275} />
          <mesh geometry={nodes['TrashBag005_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[329.945, -4.915, -60.964]} rotation={[-1.558, 0.142, -1.672]} scale={[24.306, 24.242, 16.565]} />
          <mesh geometry={nodes['Brick2_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-140, 340, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Brick2001_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-110, 400, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Brick2002_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-90, 380, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Brick2003_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[50, 300, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Brick2004_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-260, 300, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Brick2005_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[160, 550, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Brick2006_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[70, 320, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Brick2007_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[130, 480, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Brick2008_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[110, 460, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Brick2009_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[270, 410, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Brick2010_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[240, 380, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Brick2011_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[200, 570, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Brick2012_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[60, 730, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Brick2013_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[20, 740, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Brick2014_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[50, 700, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Brick2015_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-270, 570, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Brick2016_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-280, 610, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Brick2017_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-230, 550, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Brick2018_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-50, 600, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Brick2019_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-90, 610, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Brick2020_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[110, 670, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Brick2021_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-130, 990, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Brick2022_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-160, 990, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Brick2023_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-120, 1010, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Brick2024_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-80, 890, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Brick2025_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-100, 870, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Brick2026_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[100, 820, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Brick2027_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[130, 850, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Brick2028_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[170, 810, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Brick2029_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[100, 960, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Brick2030_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[130, 990, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Brick2031_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[260, 1000, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Brick2032_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[120, 650, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Brick2033_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 440, 80]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['ShopFront116_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-305, 0, 0]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['ShopFront120_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-170, 0, -305]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-100, 100, 100]} />
          <mesh geometry={nodes['Brick2034_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 460, 100]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2035_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 490, 60]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2036_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 320, 220]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2037_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 300, 200]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2038_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 440, -140]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2039_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 440, -110]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2040_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 410, -90]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2041_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 310, -50]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2042_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 330, -70]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2043_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 750, -270]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2044_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 730, -250]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2045_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 750, -200]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2046_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 670, 140]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2047_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 650, 120]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2048_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 680, 70]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2049_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 730, -60]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2050_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 700, -100]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2051_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 680, -80]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2052_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 550, 120]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2053_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 550, 150]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2054_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 570, 250]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2055_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 1030, 270]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2056_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 1010, 250]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2057_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 1020, 200]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2058_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 910, 140]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2059_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 900, 90]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2060_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 880, 70]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2061_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 810, 160]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2062_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 810, 190]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2063_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 940, -130]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2064_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 920, -110]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2065_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 920, -80]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2066_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 830, -50]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2067_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 1030, -150]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2068_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 1010, -180]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2069_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 1010, -210]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2070_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 870, -270]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2071_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[140, 340, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick2072_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[110, 400, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick2073_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[90, 380, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick2074_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-50, 300, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick2075_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[260, 300, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick2076_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-160, 550, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick2077_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-70, 320, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick2078_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-130, 480, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick2079_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-110, 460, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick2080_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-270, 410, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick2081_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-240, 380, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick2082_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-200, 570, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick2083_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-60, 730, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick2084_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-20, 740, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick2085_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-50, 700, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick2086_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[270, 570, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick2087_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[280, 610, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick2088_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[230, 550, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick2089_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[50, 600, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick2090_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[90, 610, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick2091_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-110, 670, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick2092_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[130, 990, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick2093_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[160, 990, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick2094_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[120, 1000, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick2095_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[80, 890, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick2096_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[100, 870, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick2097_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-100, 820, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick2098_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-130, 850, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick2099_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-170, 810, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick2100_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-100, 960, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick2101_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-130, 990, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick2102_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-260, 1000, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick2103_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-120, 650, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick2104_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 440, -80]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2105_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 460, -100]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2106_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 490, -60]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2107_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 320, -220]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2108_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 300, -200]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2109_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 440, 140]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2110_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 440, 110]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2111_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 410, 90]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2112_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 310, 50]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2113_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 330, 70]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2114_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 750, 270]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2115_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 730, 250]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2116_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 750, 200]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2117_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 670, -140]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2118_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 650, -120]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2119_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 680, -70]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2120_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 730, 60]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2121_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 700, 100]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2122_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 680, 80]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2123_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 550, -120]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2124_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 550, -150]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2125_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 570, -250]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2126_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 1030, -270]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2127_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 1010, -250]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2128_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 1020, -200]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2129_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 910, -140]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2130_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 900, -90]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2131_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 880, -70]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2132_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 810, -160]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2133_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 810, -190]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2134_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 940, 130]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2135_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 920, 110]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2136_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 920, 80]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2137_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 830, 50]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2138_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 1030, 150]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2139_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 1010, 180]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2140_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 1010, 210]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick2141_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 870, 270]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1001_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 190, 210]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1002_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 170, 230]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1003_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 140, 80]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1004_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 120, 60]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1005_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 140, 0]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1006_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 20, 170]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1007_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 40, 140]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1008_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 60, 210]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1009_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 80, -220]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1010_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 60, -240]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1011_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 20, -220]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1012_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 190, -280]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1013_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 180, -250]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1014_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 200, -60]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1015_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 20, 10]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1016_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[230, 190, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick1017_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[210, 170, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick1018_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[270, 70, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick1019_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[240, 60, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick1020_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[80, 50, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick1021_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[50, 60, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick1022_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[70, 90, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick1023_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-100, 190, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick1024_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-190, 100, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick1025_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-170, 80, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick1026_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-110, 90, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick1027_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-230, 20, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick1028_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-260, 30, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick1029_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 190, -210]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1030_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 170, -230]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1031_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 140, -80]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1032_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 120, -60]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1033_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 140, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1034_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 20, -170]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1035_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 40, -140]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1036_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 60, -210]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1037_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 80, 220]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1038_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 60, 240]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1039_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 20, 220]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1040_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 190, 280]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1041_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 180, 250]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1042_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 200, 60]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1043_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 20, -10]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1044_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-140, 1270, -50]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1045_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-140, 1250, -70]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1046_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-140, 1130, -200]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1047_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-140, 1130, -170]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1048_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-140, 1150, -120]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1049_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-140, 1100, -50]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1056_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-180, 1163.974, -216.733]} rotation={[-0.976, 0, Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick1057_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-210, 1177.697, -207.452]} rotation={[-0.976, 0, Math.PI]} scale={100} />
          <mesh geometry={nodes['Brick1000_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-230, 1273.757, -142.483]} rotation={[-0.976, 0, Math.PI]} scale={100} />
          <mesh geometry={nodes['ShopFront056_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[200, 770, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['ShopFront057_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[200, 510, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['ShopFront058_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[200, 250, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['ShopFront059_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 770, -200]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['ShopFront060_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 510, -200]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['ShopFront061_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[300, 250, -200]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['ShopFront062_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-200, 770, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['ShopFront063_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-200, 510, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['ShopFront064_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-200, 250, -300]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes['ShopFront065_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 770, 200]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['ShopFront066_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 510, 200]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['ShopFront067_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-300, 250, 200]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1116_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-260, 1250, -70]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1117_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-260, 1270, -50]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1118_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-260, 1100, -50]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1119_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-260, 1150, -120]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1120_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-260, 1130, -170]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
          <mesh geometry={nodes['Brick1121_Lost-Century16_0'].geometry} material={materials['Lost-Century16']} position={[-260, 1130, -200]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/building/model.glb')
